// use cases
export const GENERATE_PERIOD_STATS_USE_CASE = 'GENERATE_PERIOD_STATS_USE_CASE';
export const GET_LIST_PERIOD_STATS_USE_CASE = 'GET_LIST_PERIOD_STATS_USE_CASE';
export const GET_STATS_BY_ID = 'GET_STATS_BY_ID';

// Repositories
export const PERIOD_STATS_REPOSITORY = 'PERIOD_STATS_REPOSITORY';
export const PERIOD_REPOSITORY = 'PERIOD_REPOSITORY';
export const OPERATING_PERIOD_REPOSITORY = 'OPERATING_PERIOD_REPOSITORY';

// Services
export const PERIOD_STATS_COMMAND_SERVICE = 'PERIOD_STATS_COMMAND_SERVICE';
export const PERIOD_STATS_QUERY_SERVICE = 'PERIOD_STATS_QUERY_SERVICE';

// Events
export const PERIOD_STATS_CREATED_EVENT = 'PERIOD_STATS_CREATED_EVENT';
export const EVENT_BUS_PROVIDER = 'EVENT_BUS_PROVIDER';

// Handlers
export const CREATE_PERIOD_STATS_HANDLER = 'CREATE_PERIOD_STATS_HANDLER';
export const GET_LIST_PERIOD_STATS_HANDLER = 'GET_LIST_PERIOD_STATS_HANDLER';
export const GET_PERIOD_STATS_BY_ID_HANDLER = 'GET_PERIOD_STATS_BY_ID_HANDLER';

export const TAUNTER_SERVICE = 'TAUNTER_SERVICE';